/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SubMenus.Materias;

import com.mycompany.Clases.Materia;
import com.mycompany.DataAccessObjects.MateriaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class ActualizarMaterias extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarMaterias
     */
    public ActualizarMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        lblFk = new javax.swing.JLabel();
        txtFk = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualizar Materias");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        lblClave.setText("Clave de la materia");
        getContentPane().add(lblClave);
        lblClave.setBounds(10, 20, 160, 18);
        getContentPane().add(txtClave);
        txtClave.setBounds(10, 50, 130, 24);

        lblFk.setText("ID de la licenciatura a la que pertenece");
        getContentPane().add(lblFk);
        lblFk.setBounds(10, 100, 251, 18);
        getContentPane().add(txtFk);
        txtFk.setBounds(10, 130, 130, 24);

        lblNombre.setText("Nombre de la materia");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(10, 180, 140, 18);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(10, 210, 130, 24);

        lblId.setText("ID de la materia");
        getContentPane().add(lblId);
        lblId.setBounds(210, 20, 102, 18);
        getContentPane().add(txtId);
        txtId.setBounds(210, 50, 140, 24);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(140, 280, 120, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        MateriaDAO md = new MateriaDAO();
        Materia m = new Materia();
        String clave = "", nombre = "";
        int fk = 0, idMateria = 0;
        if(txtClave.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso la clave", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            clave = txtClave.getText();
            m.setClave(clave);
        }
        if(txtFk.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso la llave foranea", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            fk = Integer.parseInt(txtFk.getText());
            m.setFk_licenciaturaId(idMateria);
        }
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso el nombre de la materia", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            nombre = txtNombre.getText();
            m.setNombre(nombre);
        }
        if(txtId.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso el ID de la materia", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            idMateria = Integer.parseInt(txtId.getText());
            m.setIdMaterias(idMateria);
        }
        
        try {
            md.actualizar(m);
            JOptionPane.showMessageDialog(rootPane, "Materia actualizada exitosamente", "Registro actualizado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarMaterias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarMaterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblFk;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtFk;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
