/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SubMenus.Materias;

import com.mycompany.Clases.Materia;
import com.mycompany.DataAccessObjects.MateriaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class InsertarMaterias extends javax.swing.JFrame {

    /**
     * Creates new form InsertarMaterias
     */
    public InsertarMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblfk = new javax.swing.JLabel();
        txtFk = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insertar Materias");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        lblfk.setText("ID de la licenciatura a la que pertenece");
        getContentPane().add(lblfk);
        lblfk.setBounds(90, 10, 280, 18);
        getContentPane().add(txtFk);
        txtFk.setBounds(90, 40, 180, 24);

        lblClave.setText("Clave de la licenciatura");
        getContentPane().add(lblClave);
        lblClave.setBounds(90, 90, 170, 18);
        getContentPane().add(txtClave);
        txtClave.setBounds(90, 120, 190, 24);

        jLabel1.setText("Nombre de la licenciatura");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 160, 165, 18);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(90, 190, 190, 24);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar);
        btnInsertar.setBounds(150, 250, 79, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        MateriaDAO md = new MateriaDAO();
        Materia m = new Materia();
        int fk = 0;
        String nombre = "", clave = "";
        if(txtClave.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Clave no ingresada", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            clave = txtClave.getText();
            m.setClave(clave);
        }
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Nombre no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            nombre = txtNombre.getText();
            m.setNombre(nombre);
        }
        if(txtFk.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Llave foranea o ingresada", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            fk = Integer.parseInt(txtFk.getText());
            m.setFk_licenciaturaId(fk);
        }
        
        try {
            md.insertar(m);
            JOptionPane.showMessageDialog(rootPane, "Materia registrada exitosamente", "Registro insertado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(InsertarMaterias.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarMaterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblfk;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtFk;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
