-- MySQL Script generated by MySQL Workbench
-- jue 08 dic 2022 10:30:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Visual2022B
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Visual2022B
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Visual2022B` DEFAULT CHARACTER SET utf8 ;
USE `Visual2022B` ;

-- -----------------------------------------------------
-- Table `Visual2022B`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Visual2022B`.`Alumnos` (
  `idAlumnos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoP` VARCHAR(45) NOT NULL,
  `ApellidoM` VARCHAR(45) NOT NULL,
  `DoB` DATE NOT NULL,
  PRIMARY KEY (`idAlumnos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visual2022B`.`Docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Visual2022B`.`Docentes` (
  `idDocentes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoP` VARCHAR(45) NOT NULL,
  `ApellidoM` VARCHAR(45) NOT NULL,
  `DoB` DATE NOT NULL,
  PRIMARY KEY (`idDocentes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visual2022B`.`Licenciaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Visual2022B`.`Licenciaturas` (
  `idLicenciaturas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `clave` VARCHAR(5) NOT NULL,
  `REVOE` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLicenciaturas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visual2022B`.`Materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Visual2022B`.`Materias` (
  `idMaterias` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_licenciaturaId` INT UNSIGNED NOT NULL,
  `Clave` VARCHAR(5) NOT NULL,
  `Nomnbre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMaterias`),
  INDEX `fk_licenciatura_materia_idx` (`fk_licenciaturaId` ASC) ,
  CONSTRAINT `fk_licenciatura_materia`
    FOREIGN KEY (`fk_licenciaturaId`)
    REFERENCES `Visual2022B`.`Licenciaturas` (`idLicenciaturas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visual2022B`.`Inscritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Visual2022B`.`Inscritos` (
  `ins` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_alumno` INT UNSIGNED NOT NULL,
  `fk_docente` INT UNSIGNED NOT NULL,
  `fk_materia` INT UNSIGNED ZEROFILL NOT NULL,
  `ciclo` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ins`),
  INDEX `fk_alumno_inscrito_idx` (`fk_alumno` ASC) ,
  INDEX `fk_docente_inscritos_idx` (`fk_docente` ASC) ,
  INDEX `fk_materia_inscritos_idx` (`fk_materia` ASC) ,
  CONSTRAINT `fk_alumno_inscrito`
    FOREIGN KEY (`fk_alumno`)
    REFERENCES `Visual2022B`.`Alumnos` (`idAlumnos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_docente_imparte`
    FOREIGN KEY (`fk_docente`)
    REFERENCES `Visual2022B`.`Docentes` (`idDocentes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_materia_inscrito`
    FOREIGN KEY (`fk_materia`)
    REFERENCES `Visual2022B`.`Materias` (`idMaterias`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
