/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SubMenus.Alumnos;

import com.mycompany.Clases.Alumno;
import com.mycompany.DataAccessObjects.AlumnoDAO;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class ActualizarAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarAlumnos
     */
    public ActualizarAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        cbYear = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbDia = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        lblIdAlumno = new javax.swing.JLabel();
        txtIdAlumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualizar Alumno");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 52, 18);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(10, 50, 140, 24);

        jLabel2.setText("Apellido Paterno");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 105, 18);
        getContentPane().add(txtApellidoP);
        txtApellidoP.setBounds(10, 130, 140, 24);

        jLabel3.setText("Apellido Materno");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 130, 18);
        getContentPane().add(txtApellidoM);
        txtApellidoM.setBounds(10, 200, 140, 24);

        lblYear.setText("Año");
        getContentPane().add(lblYear);
        lblYear.setBounds(30, 250, 25, 18);

        lblMes.setText("Mes");
        getContentPane().add(lblMes);
        lblMes.setBounds(170, 250, 27, 18);

        lblDia.setText("Dia");
        getContentPane().add(lblDia);
        lblDia.setBounds(320, 250, 22, 18);

        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        getContentPane().add(cbYear);
        cbYear.setBounds(10, 290, 72, 24);

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        getContentPane().add(cbMes);
        cbMes.setBounds(150, 290, 72, 24);

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cbDia);
        cbDia.setBounds(300, 290, 72, 24);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(130, 340, 110, 24);

        lblIdAlumno.setText("ID del Alumno");
        getContentPane().add(lblIdAlumno);
        lblIdAlumno.setBounds(270, 20, 90, 18);
        getContentPane().add(txtIdAlumno);
        txtIdAlumno.setBounds(260, 50, 120, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        AlumnoDAO ad = new AlumnoDAO();
        String nombre = "", apellidoP = "", apellidoM = "", year = "", mes = "", dia = "";
        int idAlumno = 0, seleccionYear = 0, seleccionMes = 0, seleccionDia = 0, yi = 0, mi = 0, di = 0;
        if(txtIdAlumno.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "ID del alumno no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            idAlumno = Integer.parseInt(txtIdAlumno.getText());
        }
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Nombre no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            nombre = txtNombre.getText();
        }
        if(txtApellidoP.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Apellido paterno no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            apellidoP = txtApellidoP.getText();
        }
        if(txtApellidoM.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Apellido materno no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            apellidoM = txtApellidoM.getText();
        }
        
        seleccionYear = cbYear.getSelectedIndex();
        seleccionMes = cbMes.getSelectedIndex();
        seleccionDia = cbDia.getSelectedIndex();
        
        year = cbYear.getItemAt(seleccionYear);
        mes = cbMes.getItemAt(seleccionMes);
        dia = cbDia.getItemAt(seleccionDia);
        
        yi = Integer.parseInt(year);
        mi = Integer.parseInt(mes);
        di = Integer.parseInt(dia);
        
        //El constructor de Date nos pide restar 1900 a la cifra del año ingresado
        yi = yi-1900;
        
        Date DoB = new Date(yi, mi, di);
        
        Alumno a = new Alumno(nombre, apellidoP, apellidoM, DoB, idAlumno);
        try {
            ad.actualizar(a);
            JOptionPane.showMessageDialog(rootPane, "Datos del alumno actualizado", "Base de datos modificada", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblIdAlumno;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtIdAlumno;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
