package com.mycompany.MenuPrincipal;

import com.mycompany.MenusCategorias.MenuAlumnos;
import com.mycompany.MenusCategorias.MenuDocentes;
import com.mycompany.MenusCategorias.MenuInscritos;
import com.mycompany.MenusCategorias.MenuLicenciaturas;
import com.mycompany.MenusCategorias.MenuMaterias;

/**
 *
 * @author aspxe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAlumnos = new javax.swing.JButton();
        btnDocentes = new javax.swing.JButton();
        btnLicenciatura = new javax.swing.JButton();
        btnMateria = new javax.swing.JButton();
        btnInscritos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        btnAlumnos.setText("Alumnos");
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlumnos);
        btnAlumnos.setBounds(20, 160, 120, 24);

        btnDocentes.setText("Docentes");
        btnDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocentesActionPerformed(evt);
            }
        });
        getContentPane().add(btnDocentes);
        btnDocentes.setBounds(223, 160, 150, 24);

        btnLicenciatura.setText("Licenciaturas");
        btnLicenciatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciaturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLicenciatura);
        btnLicenciatura.setBounds(460, 160, 117, 24);

        btnMateria.setText("Materias");
        btnMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMateria);
        btnMateria.setBounds(95, 320, 130, 24);

        btnInscritos.setText("Inscritos");
        btnInscritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscritosActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscritos);
        btnInscritos.setBounds(355, 320, 130, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        MenuAlumnos ma = new MenuAlumnos();
        ma.setVisible(true);
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocentesActionPerformed
        MenuDocentes md = new MenuDocentes();
        md.setVisible(true);
    }//GEN-LAST:event_btnDocentesActionPerformed

    private void btnLicenciaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciaturaActionPerformed
        MenuLicenciaturas ml = new MenuLicenciaturas();
        ml.setVisible(true);
    }//GEN-LAST:event_btnLicenciaturaActionPerformed

    private void btnMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActionPerformed
        MenuMaterias mm = new MenuMaterias();
        mm.setVisible(true);
    }//GEN-LAST:event_btnMateriaActionPerformed

    private void btnInscritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscritosActionPerformed
        MenuInscritos mi = new MenuInscritos();
        mi.setVisible(true);
    }//GEN-LAST:event_btnInscritosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnDocentes;
    private javax.swing.JButton btnInscritos;
    private javax.swing.JButton btnLicenciatura;
    private javax.swing.JButton btnMateria;
    // End of variables declaration//GEN-END:variables
}
