/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SubMenus.Inscritos;

import com.mycompany.Clases.Inscritos;
import com.mycompany.DataAccessObjects.InscritosDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class ActualizarInscritos extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarInscritos
     */
    public ActualizarInscritos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCiclo = new javax.swing.JLabel();
        txtCiclo = new javax.swing.JTextField();
        lblIdAlumno = new javax.swing.JLabel();
        txtIdAlumno = new javax.swing.JTextField();
        lblIdDocente = new javax.swing.JLabel();
        txtIdDocente = new javax.swing.JTextField();
        lblIdMateria = new javax.swing.JLabel();
        txtIdMateria = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdInscripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualizar Inscritos");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        lblCiclo.setText("Ciclo");
        getContentPane().add(lblCiclo);
        lblCiclo.setBounds(20, 20, 33, 18);
        getContentPane().add(txtCiclo);
        txtCiclo.setBounds(20, 50, 150, 24);

        lblIdAlumno.setText("ID del alumno a inscribir");
        getContentPane().add(lblIdAlumno);
        lblIdAlumno.setBounds(20, 90, 190, 18);
        getContentPane().add(txtIdAlumno);
        txtIdAlumno.setBounds(20, 120, 150, 24);

        lblIdDocente.setText("ID del docente que impartira la clase");
        getContentPane().add(lblIdDocente);
        lblIdDocente.setBounds(20, 160, 236, 18);
        getContentPane().add(txtIdDocente);
        txtIdDocente.setBounds(20, 190, 150, 24);

        lblIdMateria.setText("ID de la materia que sera impartida");
        getContentPane().add(lblIdMateria);
        lblIdMateria.setBounds(20, 230, 227, 18);
        getContentPane().add(txtIdMateria);
        txtIdMateria.setBounds(20, 260, 150, 24);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(110, 330, 120, 24);

        jLabel1.setText("ID de inscripcion");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 20, 120, 18);
        getContentPane().add(txtIdInscripcion);
        txtIdInscripcion.setBounds(250, 50, 130, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        InscritosDAO id = new InscritosDAO();
        Inscritos i = new Inscritos();
        String ciclo = "";
        int idAlumno = 0, idDocente = 0, idMateria = 0, idInscripcion = 0;
        if(txtCiclo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            ciclo = txtCiclo.getText();
            i.setCiclo(ciclo);
        }
        if(txtIdAlumno.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            idAlumno = Integer.parseInt(txtIdAlumno.getText());
            i.setFk_alumno(idAlumno);
        }
        if(txtIdDocente.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            idDocente = Integer.parseInt(txtIdDocente.getText());
            i.setFk_docente(idDocente);
        }
        if(txtIdMateria.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            idMateria = Integer.parseInt(txtIdMateria.getText());
            i.setFk_materia(idMateria);
        }
        if(txtIdInscripcion.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
            idInscripcion = Integer.parseInt(txtIdInscripcion.getText());
            i.setIns(idInscripcion);
        }
        
        try {
            id.actualizar(i);
            JOptionPane.showMessageDialog(rootPane, "Actualizacion realizada exitosamente", "Registro actualizado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarInscritos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarInscritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCiclo;
    private javax.swing.JLabel lblIdAlumno;
    private javax.swing.JLabel lblIdDocente;
    private javax.swing.JLabel lblIdMateria;
    private javax.swing.JTextField txtCiclo;
    private javax.swing.JTextField txtIdAlumno;
    private javax.swing.JTextField txtIdDocente;
    private javax.swing.JTextField txtIdInscripcion;
    private javax.swing.JTextField txtIdMateria;
    // End of variables declaration//GEN-END:variables
}
