/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SubMenus.Inscritos;

import com.mycompany.Clases.Inscritos;
import com.mycompany.DataAccessObjects.InscritosDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class InsertarInscritos extends javax.swing.JFrame {

    /**
     * Creates new form InsertarInscritos
     */
    public InsertarInscritos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCiclo = new javax.swing.JLabel();
        txtCiclo = new javax.swing.JTextField();
        lblIdAlumno = new javax.swing.JLabel();
        txtIdAlumno = new javax.swing.JTextField();
        lblIdDocente = new javax.swing.JLabel();
        txtIdDocente = new javax.swing.JTextField();
        lblIdMateria = new javax.swing.JLabel();
        txtIdMateria = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insertar Inscritos");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        lblCiclo.setText("Ciclo");
        getContentPane().add(lblCiclo);
        lblCiclo.setBounds(30, 30, 33, 18);
        getContentPane().add(txtCiclo);
        txtCiclo.setBounds(30, 60, 160, 24);

        lblIdAlumno.setText("ID del alumno a inscribir");
        getContentPane().add(lblIdAlumno);
        lblIdAlumno.setBounds(30, 100, 190, 18);
        getContentPane().add(txtIdAlumno);
        txtIdAlumno.setBounds(30, 130, 160, 24);

        lblIdDocente.setText("ID del docente que impartira la materia");
        getContentPane().add(lblIdDocente);
        lblIdDocente.setBounds(30, 170, 250, 18);
        getContentPane().add(txtIdDocente);
        txtIdDocente.setBounds(30, 200, 160, 24);

        lblIdMateria.setText("ID de la materia");
        getContentPane().add(lblIdMateria);
        lblIdMateria.setBounds(30, 240, 102, 18);
        getContentPane().add(txtIdMateria);
        txtIdMateria.setBounds(30, 270, 160, 24);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar);
        btnInsertar.setBounds(150, 330, 79, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        InscritosDAO id = new InscritosDAO();
        Inscritos i = new Inscritos();
        String ciclo = "";
        int idAlumno = 0, idDocente, idMateria = 0;
        if(txtCiclo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "", "", JOptionPane.ERROR_MESSAGE);
        }else{
            ciclo = txtCiclo.getText();
            i.setCiclo(ciclo);
        }
        if(txtIdAlumno.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "", "", JOptionPane.ERROR_MESSAGE);
        }else{
            idAlumno = Integer.parseInt(txtIdAlumno.getText());
            i.setFk_alumno(idAlumno);
        }
        if(txtIdDocente.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "", "", JOptionPane.ERROR_MESSAGE);
        }else{
            idDocente = Integer.parseInt(txtIdDocente.getText());
            i.setFk_docente(idDocente);
        }
        if(txtIdMateria.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "", "", JOptionPane.ERROR_MESSAGE);
        }else{
            idMateria = Integer.parseInt(txtIdMateria.getText());
            i.setFk_materia(idMateria);
        }
        
        try {
            id.insertar(i);
            JOptionPane.showMessageDialog(rootPane, "Inscritos insertado exitosamente", "Registro insertado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(InsertarInscritos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarInscritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarInscritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel lblCiclo;
    private javax.swing.JLabel lblIdAlumno;
    private javax.swing.JLabel lblIdDocente;
    private javax.swing.JLabel lblIdMateria;
    private javax.swing.JTextField txtCiclo;
    private javax.swing.JTextField txtIdAlumno;
    private javax.swing.JTextField txtIdDocente;
    private javax.swing.JTextField txtIdMateria;
    // End of variables declaration//GEN-END:variables
}
