/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SubMenus.Licenciaturas;

import com.mycompany.Clases.Licenciatura;
import com.mycompany.DataAccessObjects.LicenciaturaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class ActualizarLicenciaturas extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarLicenciaturas
     */
    public ActualizarLicenciaturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRevoe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdLicenciatura = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualizar Licenciaturas");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("Clave");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 37, 18);
        getContentPane().add(txtClave);
        txtClave.setBounds(20, 50, 120, 24);

        jLabel2.setText("REVOE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 90, 52, 18);
        getContentPane().add(txtRevoe);
        txtRevoe.setBounds(20, 120, 120, 24);

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 52, 18);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(20, 190, 120, 24);

        jLabel4.setText("ID Licenciatura");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 20, 110, 18);
        getContentPane().add(txtIdLicenciatura);
        txtIdLicenciatura.setBounds(250, 50, 120, 24);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(150, 260, 110, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        LicenciaturaDAO ld = new LicenciaturaDAO();
        Licenciatura l = new Licenciatura();
        String clave = "", revoe = "", nombre = "";
        int idLicenciatura = 0;
        if(txtClave.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso la clave", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            clave = txtClave.getText();
            l.setClave(clave);
        }
        if(txtRevoe.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso el revoe", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            revoe = txtRevoe.getText();
            l.setREVOE(revoe);
        }
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso el nombre", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            nombre = txtNombre.getText();
            l.setNombre(nombre);
        }
        if(txtIdLicenciatura.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "NO ingreso el ID de la licenciatura", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            idLicenciatura = Integer.parseInt(txtIdLicenciatura.getText());
            l.setIdLicenciaturas(idLicenciatura);
        }
        
        try {
            ld.actualizar(l);
            JOptionPane.showMessageDialog(rootPane, "Registro actualizado correctamente", "Informacion modificada", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarLicenciaturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarLicenciaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarLicenciaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarLicenciaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarLicenciaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarLicenciaturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtIdLicenciatura;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRevoe;
    // End of variables declaration//GEN-END:variables
}
