/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SubMenus.Licenciaturas;

import com.mycompany.Clases.Licenciatura;
import com.mycompany.DataAccessObjects.LicenciaturaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class InsertarLicenciaturas extends javax.swing.JFrame {

    /**
     * Creates new form InsertarLicenciaturas
     */
    public InsertarLicenciaturas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRevoe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insertar Licenciaturas");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("Clave");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 37, 18);
        getContentPane().add(txtClave);
        txtClave.setBounds(130, 60, 110, 24);

        jLabel2.setText("REVOE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 100, 60, 18);
        getContentPane().add(txtRevoe);
        txtRevoe.setBounds(130, 130, 110, 24);

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 170, 70, 18);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(130, 200, 110, 24);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar);
        btnInsertar.setBounds(150, 260, 79, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        LicenciaturaDAO ld = new LicenciaturaDAO();
        Licenciatura l = new Licenciatura();
        String clave = "", revoe = "", nombre = "";
        if(txtClave.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso la clave", revoe, HEIGHT);
        }else{
            clave = txtClave.getText();
            l.setClave(clave);
        }
        if(txtRevoe.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso el revoe", revoe, HEIGHT);
        }else{
            revoe = txtRevoe.getText();
            l.setREVOE(revoe);
        }
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso el nombre", revoe, HEIGHT);
        }else{
            nombre = txtNombre.getText();
            l.setNombre(nombre);
        }
        
        try {
            ld.insertar(l);
            JOptionPane.showMessageDialog(rootPane, "Licenciatura insertada correctamente", "Informacion insertada", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(InsertarLicenciaturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarLicenciaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarLicenciaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarLicenciaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarLicenciaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarLicenciaturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRevoe;
    // End of variables declaration//GEN-END:variables
}
