/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.MenusCategorias;

import com.mycompany.Clases.Alumno;
import com.mycompany.DataAccessObjects.AlumnoDAO;
import com.mycompany.SubMenus.Alumnos.ActualizarAlumnos;
import com.mycompany.SubMenus.Alumnos.EliminarAlumnos;
import com.mycompany.SubMenus.Alumnos.InsertarAlumnos;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aspxe
 */
public class MenuAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form MenuAlumnos
     */
    public MenuAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerAlumnos = new javax.swing.JButton();
        btnIngresarAlumno = new javax.swing.JButton();
        btnActualizarAlumno = new javax.swing.JButton();
        btnEliminarAlumno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Alumnos");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        btnVerAlumnos.setText("Ver alumnos");
        btnVerAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerAlumnos);
        btnVerAlumnos.setBounds(220, 60, 120, 24);

        btnIngresarAlumno.setText("Ingresar nuevo alumno");
        btnIngresarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarAlumno);
        btnIngresarAlumno.setBounds(200, 160, 178, 24);

        btnActualizarAlumno.setText("Actualizar informacion de alumno");
        btnActualizarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarAlumno);
        btnActualizarAlumno.setBounds(170, 290, 246, 24);

        btnEliminarAlumno.setText("Eliminar alumno");
        btnEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarAlumno);
        btnEliminarAlumno.setBounds(220, 430, 135, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlumnosActionPerformed

        AlumnoDAO ad = new AlumnoDAO();
        try {
            List<Alumno> alumnos = ad.seleccionar();
            for (Alumno alumno : alumnos) {
                System.out.println("alumno = " + alumno.toString());
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnVerAlumnosActionPerformed

    private void btnIngresarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarAlumnoActionPerformed
        
        InsertarAlumnos ia = new InsertarAlumnos();
        ia.setVisible(true);
        
    }//GEN-LAST:event_btnIngresarAlumnoActionPerformed

    private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
        EliminarAlumnos ea = new EliminarAlumnos();
        ea.setVisible(true);
    }//GEN-LAST:event_btnEliminarAlumnoActionPerformed

    private void btnActualizarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAlumnoActionPerformed
        ActualizarAlumnos aa = new ActualizarAlumnos();
        aa.setVisible(true);
    }//GEN-LAST:event_btnActualizarAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAlumno;
    private javax.swing.JButton btnEliminarAlumno;
    private javax.swing.JButton btnIngresarAlumno;
    private javax.swing.JButton btnVerAlumnos;
    // End of variables declaration//GEN-END:variables
}
