/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SubMenus.Docentes;

import com.mycompany.Clases.Docente;
import com.mycompany.DataAccessObjects.DocenteDAO;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author aspxe
 */
public class ActualizarDocentes extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarDocentes
     */
    public ActualizarDocentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidoP = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        lblApellidoM = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        lblIdDocente = new javax.swing.JLabel();
        txtIdDocente = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        cbYear = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbDia = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualizar Docentes");
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(20, 20, 90, 18);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(20, 50, 110, 24);

        lblApellidoP.setText("Apellido Paterno");
        getContentPane().add(lblApellidoP);
        lblApellidoP.setBounds(20, 90, 105, 18);
        getContentPane().add(txtApellidoP);
        txtApellidoP.setBounds(20, 120, 110, 24);

        lblApellidoM.setText("Apellido Materno");
        getContentPane().add(lblApellidoM);
        lblApellidoM.setBounds(20, 160, 106, 18);
        getContentPane().add(txtApellidoM);
        txtApellidoM.setBounds(20, 190, 110, 24);

        lblIdDocente.setText("ID Docente");
        getContentPane().add(lblIdDocente);
        lblIdDocente.setBounds(240, 20, 73, 18);
        getContentPane().add(txtIdDocente);
        txtIdDocente.setBounds(240, 50, 110, 24);

        lblYear.setText("Año");
        getContentPane().add(lblYear);
        lblYear.setBounds(20, 260, 25, 18);

        lblMes.setText("Mes");
        getContentPane().add(lblMes);
        lblMes.setBounds(170, 260, 27, 18);

        lblDia.setText("Dia");
        getContentPane().add(lblDia);
        lblDia.setBounds(320, 260, 22, 18);

        cbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        getContentPane().add(cbYear);
        cbYear.setBounds(10, 290, 72, 24);

        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11" }));
        getContentPane().add(cbMes);
        cbMes.setBounds(150, 290, 72, 24);

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cbDia);
        cbDia.setBounds(300, 290, 72, 24);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(150, 340, 110, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        DocenteDAO dd = new DocenteDAO();
        Docente d = new Docente();
        String nombre = "", apellidoP = "", apellidoM = "";
        int seleccionYear = 0, seleccionMes = 0, seleccionDia = 0;
        int year = 0, mes = 0, dia = 0, idDocente = 0;
        
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No se ingreso el nombre", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            nombre = txtNombre.getText();
        }
        if(txtApellidoP.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No se ingreso el apellido paterno", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            apellidoP = txtApellidoP.getText();
        }
        if(txtApellidoM.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No se ingreso el apellido materno", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            apellidoM = txtApellidoM.getText();
        }
        if(txtIdDocente.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No ingreso el ID del docente al que se le modificara la informacion", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            idDocente = Integer.parseInt(txtIdDocente.getText());
        }
        
        seleccionYear = cbYear.getSelectedIndex();
        seleccionMes = cbMes.getSelectedIndex();
        seleccionDia = cbDia.getSelectedIndex();
        
        year = Integer.parseInt(cbYear.getItemAt(seleccionYear));
        year = year - 1900;
        mes = Integer.parseInt(cbMes.getItemAt(seleccionMes));
        dia = Integer.parseInt(cbDia.getItemAt(seleccionDia));
        
        Date DoB = new Date(year, mes, dia);
        d.setNombre(nombre);
        d.setApellidoP(apellidoP);
        d.setApellidoM(apellidoM);
        d.setDoB(DoB);
        d.setIdDocentes(idDocente);
        try {
            dd.actualizar(d);
            JOptionPane.showMessageDialog(rootPane, "Se ha actualizado la informacion del docente", "Registro actualizado", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ActualizarDocentes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarDocentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarDocentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbYear;
    private javax.swing.JLabel lblApellidoM;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblIdDocente;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtIdDocente;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
